name: financetrack
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # --- Core Firebase & Auth ---
  cloud_firestore: ^5.5.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.1.0
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.0.7
  camera: ^0.10.5
  cloud_functions: ^5.6.2
  cunning_document_scanner: ^1.4.0
  image_cropper: ^8.0.2

  # --- UI & Utilities ---
  splash_master: ^0.0.3    
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  edge_detection: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  

# --- CONFIGURATION: APP ICON ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 

flutter:
  assets:
    - assets/logo.png  # <--- MAKE SURE THIS IS LISTED
  uses-material-design: true